import { defineField, defineType } from "sanity";

export default defineType({
  name: "servicePage",
  title: "Service Page",
  type: "document",
  groups: [
    { name: "headline", title: "Headline" },
    { name: "bookACall", title: "Book a Call" },
    { name: "problems", title: "Problems" },
    { name: "solutions", title: "Solutions" },
    { name: "results", title: "Results" },
    { name: "plans", title: "Plans" },
    { name: "calendly", title: "Calendly" },
    { name: "faq", title: "FAQ" },
  ],
  fields: [
    defineField({
      name: "slug",
      title: "Page",
      type: "string",
      options: {
        list: [
          { title: "Ad Creatives", value: "ad-creatives" },
          { title: "Organic Content / YouTube", value: "organic-content-youtube" },
          { title: "SaaS Videos", value: "saas-videos" },
        ],
        layout: "radio",
      },
      validation: (Rule) => Rule.required(),
      readOnly: ({ document }) => !!document?.slug,
    }),
    defineField({
      name: "sectionLabel",
      title: "Section Label (small text above headline)",
      type: "string",
      group: "headline",
      description: "e.g. Ad Creatives, Organic Content / YouTube",
    }),
    defineField({
      name: "headlineTitle",
      title: "Headline (before highlight)",
      type: "string",
      group: "headline",
      description: "Text before the highlighted phrase",
    }),
    defineField({
      name: "headlineHighlight",
      title: "Headline (highlighted phrase)",
      type: "string",
      group: "headline",
    }),
    defineField({
      name: "headlineTitleAfter",
      title: "Headline (after highlight)",
      type: "string",
      group: "headline",
    }),
    defineField({
      name: "headlineSubtitle",
      title: "Headline Subtitle",
      type: "text",
      rows: 3,
      group: "headline",
    }),
    defineField({
      name: "bookACallHeading",
      title: "Book a Call Heading",
      type: "string",
      group: "bookACall",
    }),
    defineField({
      name: "bookACallCta",
      title: "Book a Call Button Text",
      type: "string",
      initialValue: "Book Strategy Call",
      group: "bookACall",
    }),
    defineField({
      name: "problemsLabel",
      title: "Problems Section Label",
      type: "string",
      initialValue: "Problems",
      group: "problems",
    }),
    defineField({
      name: "problemsTitle",
      title: "Problems Section Title",
      type: "string",
      initialValue: "What clients are usually going through",
      group: "problems",
    }),
    defineField({
      name: "problems",
      title: "Problems",
      type: "array",
      of: [{ type: "problemSolutionItem" }],
      group: "problems",
    }),
    defineField({
      name: "solutionsLabel",
      title: "Solutions Section Label",
      type: "string",
      initialValue: "Solutions",
      group: "solutions",
    }),
    defineField({
      name: "solutionsTitle",
      title: "Solutions Section Title",
      type: "string",
      initialValue: "How we fix it",
      group: "solutions",
    }),
    defineField({
      name: "solutions",
      title: "Solutions",
      type: "array",
      of: [{ type: "problemSolutionItem" }],
      group: "solutions",
    }),
    defineField({
      name: "resultsLabel",
      title: "Results Section Label",
      type: "string",
      initialValue: "Results",
      group: "results",
    }),
    defineField({
      name: "resultsTitle",
      title: "Results Section Title",
      type: "string",
      group: "results",
    }),
    defineField({
      name: "results",
      title: "Results",
      type: "array",
      of: [{ type: "resultItem" }],
      group: "results",
    }),
    defineField({
      name: "plansLabel",
      title: "Plans Section Label",
      type: "string",
      initialValue: "Plans",
      group: "plans",
    }),
    defineField({
      name: "plansTitle",
      title: "Plans Section Title",
      type: "string",
      group: "plans",
    }),
    defineField({
      name: "plansSubtitle",
      title: "Plans Section Subtitle",
      type: "text",
      rows: 2,
      group: "plans",
    }),
    defineField({
      name: "plans",
      title: "Plans",
      type: "array",
      of: [{ type: "servicePlan" }],
      group: "plans",
    }),
    defineField({
      name: "calendlyTitle",
      title: "Calendly Title",
      type: "string",
      group: "calendly",
    }),
    defineField({
      name: "calendlySubtitle",
      title: "Calendly Subtitle",
      type: "text",
      rows: 2,
      group: "calendly",
    }),
    defineField({
      name: "faqLabel",
      title: "FAQ Section Label",
      type: "string",
      initialValue: "FAQs",
      group: "faq",
    }),
    defineField({
      name: "faqTitle",
      title: "FAQ Section Title",
      type: "string",
      group: "faq",
    }),
    defineField({
      name: "faqHighlightedWord",
      title: "FAQ Highlighted Word",
      type: "string",
      group: "faq",
    }),
    defineField({
      name: "faqItems",
      title: "FAQ Items",
      type: "array",
      of: [{ type: "faqItem" }],
      group: "faq",
    }),
  ],
  preview: {
    select: { slug: "slug" },
    prepare({ slug }) {
      const titles: Record<string, string> = {
        "ad-creatives": "Ad Creatives",
        "organic-content-youtube": "Organic Content / YouTube",
        "saas-videos": "SaaS Videos",
      };
      return { title: titles[slug as string] || slug || "Service Page" };
    },
  },
});
